# This workflow demonstrates provides GitHub instructions to run a Selenium test with all three browsers: Chrome, FireFox or Edge browser

name: Selenium Test on All Browsers (Paralell Jobs)

on:
  - workflow_dispatch   # when the user presses a button

jobs:
  test:
    name: Selenium Testing - ${{ matrix.browser }}
    runs-on: ubuntu-latest

    container:
      image: node:23

    strategy:
      fail-fast: false                                          # ensures that all jobs within the matrix will complete their execution, regardless of individual job failures
      matrix:
        browser: ['chrome', 'firefox', 'edge']                  # strategy.matrix allows a single job definition to have multiple inputs

    services:
      selenium:
        image: selenium/standalone-${{ matrix.browser }}        # see https://hub.docker.com/u/selenium
        options: --shm-size=2gb

    steps:
      # Step 1 - Copy the code into our Ubuntu Container
      - uses: actions/checkout@v4

      # Step 2 - Install common dependencies
      - uses: actions/setup-node@v4
        with:
          node-version: '23'
          cache: 'npm'

      # Step 3 - Perform a clean and reproducible installation of Node.js project dependencies
      - run: npm ci

      # Step 4 - Executes the script defined under the "test" property within the "scripts" object in a project's package.json file.
      - run: npm run test
        env:
          BROWSER: ${{ matrix.browser }}

      # Step 5 - Upload the screenshots as artifacts so we can view them
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ matrix.browser }}
          path: screenshots/
